### ISSUE TITLE
Write Plotting Script

### ISSUE THREAD

**Issue by bmd** [bmd/text-stats#8]
#### Part 1
- [ ] Plot individual curves for all self-vs-self comparisons
- [ ] Plot individual curves for all text-vs-text comparisons
- [ ] Plot individual curves for all praiectus vs praiectus comparisons
#### Part 2
- [ ] Plot combined curve for self comparisons vs combined curve for text comparisons
- [ ] Plot individual praiectus curves against self vs self curve
#### Part 3
- [ ] Calculate KDE function for each distribution
- [ ] Come up with 90% breakpoint for texts having diff. authors.
